language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
cache:
 directories:
   - /home/travis/.julia
addons:
  apt_packages:
    - gfortran
before_install:
  - julia -e '(VERSION >= v"0.7" && using Pkg); Pkg.update()'
after_success:
  - julia -e '(VERSION >= v"0.7" && using Pkg); Pkg.add("Coverage"); cd(Pkg.dir("PowerModels")); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'if VERSION >= v"0.7" using Pkg; Pkg.add("Documenter"); import PowerModels; include(joinpath(dirname(pathof(PowerModels)), "..", "docs", "make.jl")) end'